default: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: websocket_test_production

development:
  <<: *default

test:
  adapter: test

production:
  <<: *default
